### ISSUE TITLE
Ugrade to Debian stable 10 ?

### ISSUE THREAD

**Issue by vindarel** [daewok/lisp-devel-docker#5]
Hello,

Would it be possible to update the image to Debian 10 "buster", the current stable?

thanks

**Comment by daewok** [comment]
Sure, I'll work on that! I missed that a new version was out.

**Comment by daewok** [comment]
Done, was much easier than I expected! The image no longer contains ABCL (at least until they cut 1.6.0) and one library was missing from Buster (`libsmokeqt4-dev`), I forget which library in Quicklisp wanted that, though.

**Comment by vindarel** [comment]
Great, thank you! I had to use the debian 10 image for a project and I could appreciate that this image contains all the required dependencies. By the way, how do you get them?… manually I suppose?

**Comment by daewok** [comment]
I wrote up a script that attempted to load everything in Quicklisp and quit when it found one it couldn't load. I'd then add the dependencies and start again. It's been a while since I've done that, I'm sure there are probably new systems in Quicklisp with dependencies this doesn't have. I really need to find that script again and try to automate it for every new Quicklisp release.
